services:
  front:
    image: front
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8888:80
